# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAMAnimatedTabBarDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RAMAnimatedTabBarController'
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'ContactsKit'

end
